### PR TITLE
set up phpunit and add some unit tests

### PR DESCRIPTION
**Pull request by doug7410**
This PR looks like it has a lot of files because I added the code coverage report. You might want me to ignore that.

### CODE REVIEW

**Comment by recycledbeans** [comment]
Hey, I think this is just about ready to go! The only thing I think we're going to have to do is change the requirement in composer.json to be php 7.0 or greater.

**Comment by doug7410** [comment]
I got Travis CI to pass. I had to change a few things for PHP 7.0 . I'm not sure how to fix the issues with Style CI though.

**Comment by recycledbeans** [comment]
Awesome -- I'm not worried about the StyleCI failure. I think the styles can be applied afterward. Thanks for the contribution!

**Review by recycledbeans — APPROVED** [review]

**Comment by doug7410** [comment]
Anytime bunny! 🐰lol

**Pull request merged**
